FROM golang:1.25.13-alpine AS build
WORKDIR /src
COPY go.mod go.sum ./
RUN go mod download
COPY cmd ./cmd
COPY internal ./internal
COPY web ./web
RUN CGO_ENABLED=0 go build -o /bin/fake-siem ./cmd/fakesiem

FROM alpine:3.20
COPY --from=build /bin/fake-siem /bin/fake-siem
EXPOSE 9200
USER 65534:65534
ENTRYPOINT ["/bin/fake-siem"]
