(() => {
  "use strict";
  const els = {
    status: document.getElementById("global-status"), dot: document.querySelector(".status-dot"), readiness: document.getElementById("readiness-label"), freshness: document.getElementById("freshness-label"),
    profile: document.getElementById("profile-label"), mode: document.getElementById("mode-label"), policy: document.getElementById("policy-label"), window: document.getElementById("window-label"), refresh: document.getElementById("last-refresh"), reset: document.getElementById("reset-note"),
    kpis: document.getElementById("kpis"), trend: document.getElementById("trend-chart"), funnel: document.getElementById("funnel"), alerts: document.getElementById("alerts"), alertCount: document.getElementById("alert-count"), controls: document.getElementById("control-status"), routing: document.getElementById("routing-breakdown"), audit: document.getElementById("audit-breakdown"), limits: document.getElementById("limit-breakdown"), canary: document.getElementById("canary-stat"), leaderboard: document.getElementById("leaderboard"), leaderboardEmpty: document.getElementById("leaderboard-empty"), connection: document.getElementById("connection-state"),
    windowFilter: document.getElementById("window-filter"), actionFilter: document.getElementById("action-filter"), providerFilter: document.getElementById("provider-filter"), stageFilter: document.getElementById("stage-filter"), refreshButton: document.getElementById("refresh-button")
  };
  const format = value => new Intl.NumberFormat().format(Number(value || 0));
  const query = () => {
    const params = new URLSearchParams({ window: els.windowFilter.value });
    [["action", els.actionFilter.value], ["provider_class", els.providerFilter.value], ["source_stage", els.stageFilter.value]].forEach(([key, value]) => { if (value) params.set(key, value); });
    return params.toString();
  };
  const getJSON = async path => { const response = await fetch(path, { credentials: "same-origin", cache: "no-store", headers: { Accept: "application/json" } }); if (!response.ok) throw new Error(`operator API ${response.status}`); return response.json(); };
  const text = (node, value) => { node.textContent = value == null ? "" : String(value); return node; };
  const clear = node => { while (node.firstChild) node.removeChild(node.firstChild); };
  const item = (tag, className, value) => { const node = document.createElement(tag); if (className) node.className = className; if (value !== undefined) node.textContent = value; return node; };
  const safeDetailURL = value => { const candidate = String(value || "/ready"); return candidate.startsWith("/") && !candidate.startsWith("//") && !candidate.includes("\\") ? candidate : "/ready"; };

  function renderOverview(data) {
    const status = data.status || {}; const readiness = status.readiness || {}; const freshness = data.freshness || {};
    text(els.profile, `Profile ${status.deployment_profile || "—"}`); text(els.mode, `Mode ${status.security_mode || "—"}`);
    const policy = status.policy || {}; text(els.policy, `Policy ${policy.sequence ? `#${policy.sequence} ${policy.hash || ""}` : (policy.id || "—")}`); text(els.window, `Window ${data.window && data.window.requested || "—"}`);
    const readyLabel = readiness.state === "healthy" || readiness.state === "ready" ? "Protection ready" : `Protection ${readiness.state || "unavailable"}`; text(els.readiness, readyLabel); text(els.freshness, `${freshness.status || "unknown"} · ${freshness.age_seconds || 0}s since event`); text(els.refresh, new Date(data.generated_at).toLocaleTimeString()); text(els.reset, `Aggregate reset ${new Date(data.reset.reset_at).toLocaleString()} · ${data.reset.durable ? "durable" : "process-local"}`);
    els.dot.className = `status-dot ${readiness.state === "degraded" ? "degraded" : readiness.state === "healthy" || readiness.state === "ready" ? "" : "incident"}`;
    clear(els.kpis); (data.kpis || []).forEach(kpi => { const card = item("article", "kpi"); card.title = `${kpi.definition} Owner/action: ${kpi.owner_action}`; card.append(item("h2", "", kpi.label), item("strong", "kpi-value", format(kpi.value))); const foot = item("div", "kpi-foot"); const comparison = kpi.comparison_available ? `${kpi.delta_percent >= 0 ? "+" : ""}${kpi.delta_percent}% vs prior` : "No comparison"; foot.append(item("span", `trend-${kpi.trend}`, comparison)); foot.append(item("span", "", "· hover for definition")); card.append(foot); els.kpis.append(card); });
    renderFunnel(data.funnel || {}); renderControls(status.components || []);
  }

  function renderFunnel(funnel) { clear(els.funnel); const rows = [["Inspected", funnel.inspected], ["Findings", funnel.findings], ["Transformed / blocked", funnel.transformed_or_blocked], ["Forwarded", funnel.forwarded]]; const max = Math.max(...rows.map(row => Number(row[1] || 0)), 1); rows.forEach(([label, value]) => { const row = item("div", "funnel-row"); row.append(item("span", "", label)); const track = item("div", "funnel-track"); const fill = item("div", "funnel-fill"); fill.style.width = `${Math.max(Number(value || 0) / max * 100, value ? 2 : 0)}%`; track.append(fill); row.append(track, item("strong", "", format(value))); els.funnel.append(row); }); }

  function renderTrend(data) { clear(els.trend); const points = (data.points || []).slice(-12); const max = Math.max(...points.flatMap(point => [point.protected, point.forwarded, point.findings].map(Number)), 1); const grid = item("div", "trend-grid"); points.forEach(point => { const col = item("div", "trend-col"); const bars = item("div", "trend-bars"); [[point.protected, "protected"], [point.forwarded, "forwarded"], [point.findings, "findings"]].forEach(([value, kind]) => { const bar = item("div", `bar ${kind}`); bar.style.height = `${Math.max(Number(value || 0) / max * 100, value ? 2 : 0)}%`; bar.title = `${kind}: ${format(value)}`; bar.setAttribute("aria-label", `${kind} ${format(value)}`); bars.append(bar); }); col.append(bars, item("span", "trend-label", new Date(point.timestamp).toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" }))); grid.append(col); }); els.trend.append(grid); }

  function renderCounts(node, values, emptyLabel) { clear(node); const rows = (values || []).slice(0, 8); if (!rows.length) { node.append(item("span", "muted", emptyLabel)); return; } rows.forEach(row => { const line = item("div", "metric-row"); line.append(item("span", "", row.key), item("strong", "", format(row.count))); node.append(line); }); }
  function renderBreakdown(data, status) { renderCounts(els.routing, data.provider_classes, "No route events in window"); clear(els.audit); const audit = status.audit || {}; [["State", audit.state || "unavailable"], ["Queue bytes", format(audit.queue_bytes)], ["Oldest age", `${format(audit.oldest_age_seconds)}s`], ["Exporter", audit.exporter_state || "unavailable"]].forEach(([key, value]) => { const line = item("div", "metric-row"); line.append(item("span", "", key), item("strong", "", value)); els.audit.append(line); }); (data.audit || []).slice(0, 3).forEach(row => { const line = item("div", "metric-row"); line.append(item("span", "", `Events ${row.key}`), item("strong", "", format(row.count))); els.audit.append(line); }); renderCounts(els.limits, data.runtime_limits, "No admission-limit events in window"); text(els.canary, format(data.canary_disagreements)); renderLeaderboard(data.rule_subtypes || data.categories); }
  function renderLeaderboard(values) { clear(els.leaderboard); const rows = (values || []).slice(0, 8); els.leaderboardEmpty.hidden = rows.length > 0; const max = Math.max(...rows.map(row => Number(row.count || 0)), 1); rows.forEach(row => { const line = item("div", "leader-row"); const label = item("div", "leader-label"); label.append(item("strong", "", row.key), item("span", "", "bounded category / subtype")); const track = item("div", "leader-track"); const fill = item("div", "leader-fill"); fill.style.width = `${Math.max(Number(row.count || 0) / max * 100, 2)}%`; track.append(fill); line.append(label, track, item("strong", "leader-count", format(row.count))); els.leaderboard.append(line); }); }
  function renderControls(components) { clear(els.controls); const rows = components.length ? components : [{ name: "readiness", state: "unavailable", detail: "No status provider" }]; rows.forEach(component => { const line = item("div", "status-row"); line.append(item("span", "", component.name)); line.append(item("span", `status-pill ${component.state}`, component.state)); els.controls.append(line); }); }
  function renderAlerts(data) { clear(els.alerts); const alerts = data.alerts || []; text(els.alertCount, alerts.length ? `${alerts.length} active alert${alerts.length === 1 ? "" : "s"}` : "No active alerts"); if (!alerts.length) { els.alerts.append(item("p", "muted", "Protection controls are healthy for the selected view.")); return; } alerts.forEach(alert => { const severity = ["high", "medium", "low"].includes(alert.severity) ? alert.severity : "medium"; const row = item("article", `alert ${severity}`); row.append(item("span", "alert-dot")); const body = item("div"); body.append(item("h3", "", alert.title), item("p", "", alert.detail)); const link = document.createElement("a"); link.href = safeDetailURL(alert.detail_url); link.textContent = "Open sanitized detail"; row.append(body, link); els.alerts.append(row); }); }

  let delay = 2000; let timer = null; let inFlight = false;
  async function update() { if (inFlight) return; inFlight = true; clearTimeout(timer); try { const suffix = query(); const [overview, series, breakdown, alerts] = await Promise.all([getJSON(`/api/dashboard/v2/overview?${suffix}`), getJSON(`/api/dashboard/v2/timeseries?${suffix}`), getJSON(`/api/dashboard/v2/breakdown?${suffix}`), getJSON(`/api/dashboard/v2/alerts?${suffix}`)]); renderOverview(overview); renderTrend(series); renderBreakdown(breakdown, overview.status || {}); renderAlerts(alerts); text(els.connection, "Live · polling every 2s"); delay = 2000; } catch (_) { text(els.connection, `Disconnected · retrying in ${Math.round(delay / 1000)}s`); text(els.freshness, "Dashboard API unavailable"); els.dot.className = "status-dot incident"; delay = Math.min(delay * 2, 30000); } finally { inFlight = false; timer = window.setTimeout(update, delay); } }
  [els.windowFilter, els.actionFilter, els.providerFilter, els.stageFilter].forEach(control => control.addEventListener("change", update)); els.refreshButton.addEventListener("click", update); update();
})();
